services:
  postgres:
    image: postgres:18.1-alpine3.22
    container_name: mailsangja-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mailsangja}
      POSTGRES_USER: ${POSTGRES_USER:-mailsangja}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mailsangja}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mailsangja}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine3.22
    container_name: mailsangja-redis
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis-data:
