services:
  postgres:
    image: postgres:18.1-alpine3.22
    container_name: mailsangja-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mailsangja}
      POSTGRES_USER: ${POSTGRES_USER:-mailsangja}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mailsangja}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mailsangja}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine3.22
    container_name: mailsangja-redis
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    container_name: mailsangja-core
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-mailsangja}
      DB_USERNAME: ${POSTGRES_USER:-mailsangja}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-mailsangja}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis-data:
